### ISSUE TITLE
The copyright issue

### ISSUE THREAD

**Issue by hieulq** [HPCC-Cloud-Computing/CAL_Appliances#2]
@daikk115 so your name is Mischback?

**Comment by daikk115** [comment]
@hieulq 
Ops! I'm forgot that.

First of all, I just updated project metadata: [https://github.com/cloudcomputinghust/CAL_Appliances/tree/master/fcap](https://github.com/cloudcomputinghust/CAL_Appliances/tree/master/fcap)

Then, I have updated[ fcap structure describes](https://github.com/cloudcomputinghust/CAL_Appliances/blob/master/describes/fcap-structure.md) with referencing to [Mischback project](https://github.com/Mischback/django-project-skeleton).

It's ok? I don't see any licence at Mischback project template, so I just referenced to it.

**Comment by hieulq** [comment]
Better remove author name and put a sentence state that your product is forked from his.

**Comment by daikk115** [comment]
I have removed author like this:
[https://github.com/cloudcomputinghust/CAL_Appliances/blob/master/fcap/README.md](https://github.com/cloudcomputinghust/CAL_Appliances/blob/master/fcap/README.md)
